// const data = [
//   {
//     name: "Aries",
//     slug: "aries",
//     element: "Fire",
//     rulingPlanet: "Mars",
//     symbol: "The Ram",
//     compatibility: ["Leo", "Sagittarius"],
//     luckyNumbers: [1, 9, 19],
//     luckyColor: "Red",
//     luckyDay: "Tuesday",
//     image: "/images/aries.jpeg",
//     strengths: ["Courageous", "Determined", "Confident"],
//     weaknesses: ["Impatient", "Moody", "Short-tempered"],
//     description:
//       "Aries loves to be number one, so its no surprise that these audacious rams are the first sign of the zodiac. Bold and ambitious, Aries dives headfirst into even the most challenging situations. Read your sign's full profile here.",
//   },
//   {
//     name: "Taurus",
//     slug: "taurus",
//     element: "Earth",
//     rulingPlanet: "Venus",
//     symbol: "The Bull",
//     compatibility: ["Virgo", "Capricorn"],
//     luckyNumbers: [2, 6, 9, 12, 24],
//     luckyColor: "Green",
//     luckyDay: "Friday",
//     image: "/images/taurus.jpeg",
//     strengths: ["Reliable", "Patient", "Practical"],
//     weaknesses: ["Stubborn", "Possessive", "Uncompromising"],
//     description:
//       "Taurus is an earth sign represented by the bull. Like their celestial spirit animal, Taureans enjoy relaxing in serene, bucolic environments surrounded by soft sounds, soothing aromas, and succulent flavors. Read your sign's full profile here.",
//   },
//   {
//     name: "Gemini",
//     slug: "gemini",
//     element: "Air",
//     rulingPlanet: "Mercury",
//     symbol: "The Twins",
//     compatibility: ["Libra", "Aquarius"],
//     luckyNumbers: [5, 7, 14, 23],
//     luckyColor: "Yellow",
//     luckyDay: "Wednesday",
//     image: "/images/gemini.jpeg",
//     strengths: ["Gentle", "Affectionate", "Curious"],
//     weaknesses: ["Indecisive", "Nervous", "Inconsistent"],
//     description:
//       "Have you ever been so busy that you wished you could clone yourself just to get everything done? That’s the Gemini experience in a nutshell. Appropriately symbolized by the celestial twins, this air sign was interested in so many pursuits that it had to double itself.",
//   },
//   {
//     name: "Cancer",
//     slug: "cancer",
//     element: "Water",
//     rulingPlanet: "Moon",
//     symbol: "The Crab",
//     compatibility: ["Scorpio", "Pisces"],
//     luckyNumbers: [2, 3, 15, 20],
//     luckyColor: "Silver",
//     luckyDay: "Monday",
//     image: "/images/cancer.jpeg",
//     strengths: ["Loyal", "Adaptable", "Sympathetic"],
//     weaknesses: ["Moodiness", "Overemotional", "Sensitive"],
//     description:
//       "Cancer is a cardinal water sign. Represented by the crab, this crustacean seamlessly weaves between the sea and shore, representing Cancer’s ability to exist in both emotional and material realms. Cancers are highly intuitive and their psychic abilities manifest in tangible spaces: For instance, Cancers can effortlessly pick up the energies in a room.",
//   },
//   {
//     name: "Leo",
//     slug: "leo",
//     element: "Fire",
//     rulingPlanet: "Sun",
//     symbol: "The Lion",
//     compatibility: ["Aries", "Sagittarius"],
//     luckyNumbers: [1, 4, 10, 13],
//     luckyColor: "Gold",
//     luckyDay: "Sunday",
//     image: "/images/leo.jpeg",
//     strengths: ["Generous", "Warmhearted", "Creative"],
//     weaknesses: ["Arrogant", "Stubborn", "Self-centered"],
//     description:
//       "Roll out the red carpet, because Leo has arrived. Leo is represented by the lion and these spirited fire signs are the kings and queens of the celestial jungle. They’re delighted to embrace their royal status: Vivacious, theatrical, and passionate, Leos love to bask in the spotlight and celebrate themselves.",
//   },
// ];

// export default data;
